### ISSUE TITLE
Display a placeholder image via HDMI

### ISSUE THREAD

**Issue by shutej** [gokrazy/hello#1]
I was expecting to gokr-packer this onto a card and see output over an HDMI port.

I see nothing from the Pi.  This may be made somewhat more complex by me trying to get this to work on a Raspberry Pi Zero W (the new wireless model), but supposedly that shares a chip/architecture with the Pi 3?

I suggest adding some documentation on how you can verify that the program works.  (The Pi zero has no hard network port, so no DHCP lease and no web UI ... nor do I care to have one, I suspect this should run headless?)

I also tried the following, but got nothing visible.  It may be useful to include functionality like this in this package...

```go
package main

import (
	"os"
	"time"
)

// https://www.raspberrypi.org/forums/viewtopic.php?f=31&t=12530
var (
	none = []byte("none\n")
	off  = []byte("0\n")
	on   = []byte("255\n")
)

func main() {
	trigger, _ := os.Create("/sys/class/leds/led0/trigger")
	trigger.Write(none)
	trigger.Close()

	for i := 0; true; i++ {
		var value []byte
		switch i % 2 {
		case 0:
			value = off
		case 1:
			value = on
		}

		brightness, _ := os.Create("/sys/class/leds/led0/brightness")
		brightness.Write(value)
		brightness.Close()

		time.Sleep(250 * time.Millisecond)
	}
}
```

**Comment by stapelberg** [comment]
> I was expecting to gokr-packer this onto a card and see output over an HDMI port.

I haven’t tested whether there will be any output on the HDMI port. I know that the Debian Raspberry Pi 3 image (which uses a very similar kernel) does not produce any output on the HDMI port, so my assumption is that there won’t be any.

I don’t know what’s required for HDMI output, but it would be cool if we could produce a placeholder image to guide people into the right direction.

> I see nothing from the Pi. This may be made somewhat more complex by me trying to get this to work on a Raspberry Pi Zero W (the new wireless model), but supposedly that shares a chip/architecture with the Pi 3?

Unfortunately, the Raspberry Pi Zero W uses the older BCM2835 SoC, which is not arm64, so gokrazy won’t run on it. You’ll need a Raspberry Pi 3. See also https://www.reddit.com/r/golang/comments/5xgf8u/gokrazy_a_purego_userland_for_your_raspberry_pi_3/dei7b2m/

This is a common misconception (you are the fourth person to bring it up), so it’s worth updating the website and program output.

> I suggest adding some documentation on how you can verify that the program works. (The Pi zero has no hard network port, so no DHCP lease and no web UI ... nor do I care to have one, I suspect this should run headless?)

The quickstart (https://gokrazy.github.io/quickstart.html) briefly mentions the web interface, but we should make the gokr-packer output more explicit. Filed https://github.com/gokrazy/tools/issues/4

**Comment by stapelberg** [comment]
The quickstart and gokr-packer output are now updated.

I’ve retitled the issue to reflect the only bit of work left, but I have no idea how it could be accomplished, and no immediate urgency to explore it. Any help welcome :).

**Comment by shutej** [comment]
Thanks, this has been a huge help.

**Comment by stapelberg** [comment]
Oh, I just came across this issue again.

Since the last update, we now have https://github.com/gokrazy/fbstatus which does display diagnostics via HDMI.

The documentation (e.g. https://gokrazy.org/quickstart/) includes the package in the example invocations.
